#Written by SmartGit. Trailing spaces might matter!
#Wed Dec 14 13:47:33 BRT 2022
smartgit.avatar.size=32
smartgit.avatar.small.size=16
smartgit.changes.maximumFileSize=10000000
smartgit.copyID.copyFull=true
smartgit.debugMenu=true
smartgit.log.commits.showCommitCountInTabTitle=true
smartgit.log.details.headerValueSeparator=, 
smartgit.log.graph.author.maxLength=10
smartgit.pull.honorRemoteSelection=true
smartgit.repositories.maxNonFavorite=20
smartgit.svn.authorsfile=F\:/SmartGit/.settings/svn_authors.txt
smartgit.ui.errorDialog.markdownSupport=false
smartgit.ui.systemtray.enabled=false
