git:
  projectToolBar-17:
    items:
    - {id: fetch}
    - {id: sync}
    - {id: push}
    - {stretching: false}
    - {id: commit}
    - {stretching: true}
    - {id: stage}
    - {id: indexEditor}
    - {id: unstage}
    - {stretching: false}
    - {id: discard}
    - {stretching: false}
    - {id: stashSave}
    - {id: stashApply}
    - {id: delete}
    - {stretching: true}
    - {id: logRepository}
    - {id: annotate}
    - {id: investigate}
    - {stretching: true}
    - {id: flowContext}
    - {stretching: false}
    - {id: merge}
    - {id: rebaseHeadTo}
    textBelowIcon: true
    visible: false
  logToolBar-18.2:
    items:
    - {id: fetch}
    - {id: push}
    - {stretching: false}
    - {id: flowContext}
    - {stretching: false}
    - {id: merge}
    - {id: rebaseHeadTo}
    - {id: commit}
    - {stretching: true}
    - {id: stage}
    - {id: indexEditor}
    - {id: unstage}
    - {stretching: false}
    - {id: discard}
    - {stretching: false}
    - {id: stashSave}
    - {id: stashApply}
    - {stretching: true}
    - {id: cherryPick}
    - {id: delete}
    - {id: branchAddTag}
    - {stretching: true}
    - {id: log}
    - {id: annotate}
    - {id: investigate}
    - {stretching: true}
    - {id: windowLayoutSetMain}
    - {id: windowLayoutSetReview}
    textBelowIcon: true
    visible: false
filterConfiguration:
  patterns: []
  regularExpressions: false
